### ISSUE TITLE
How to create custom user provider to feature

### ISSUE THREAD

**Issue by seetharamireddy540** [togglz/togglz#140]
Hi,

I have webservice (JAX-RS) and i need to control the processing of this service  base on certen input parameters

Ex : Web Service input request has filed name " clientID", and in my application if the client id is Cretan list of value i have to enable one feature , if the client is not in approved list then i shouldn't do that functionality alone.

I am looking into possible options in Togglz instead build my own if -else condition logic across application.

I couldn't able to find the much documentation how to do it use case.
Can you pls let me know if we can use Togglz for this use case or not ?

Thanks in advance for your help.

Regards
Seetharmaireddy Mittala

**Comment by chkal** [comment]
Basically you can do this with a custom user provider. I recommend do try this:

As soon as you get the information about the user (within your JAX-RS resource method or in some kind of JAX-RS SPI like a ContainerResponseFilter) you could store the name of the client as a HttpServletRequest attribute.
 
Now you can implement a [custom user provider](http://www.togglz.org/documentation/authentication.html#custom). You can use Togglz' [HttpServletRequestHolder](http://www.togglz.org/apidocs/2.2.0.Final/org/togglz/servlet/util/HttpServletRequestHolder.html) to obtain the current request. Now you can read the request attribute and create an FeatureUser to return from the UserProvider.

I guess it should work fine this way.

BTW: Please post such questions on the [user list](https://groups.google.com/forum/?fromgroups#!forum/togglz-users) instead of opening a ticket. Thanks.
