### ISSUE TITLE
Add StateRepositoryProvider concept

### ISSUE THREAD

**Issue by marceloverdijk** [togglz/togglz#148]
Just like there is a `ActivationStrategyProvider` and a `FeatureProvider`.
It should be able to set this `StateRepositoryProvider` in the`FeatureManagerBuilder`.

**Comment by chkal** [comment]
Note sure if I understand this request.

Togglz needs a list of all available activation strategies to populate the dropdown of the admin console so that the user is able to select one strategy from the list of all available ones. That's why this provider exists. Back then only the JDK ServiceLoader mechanism was supported. Later we added this provider interface so that people can also register available implementations programmatically.

For state repositories this doesn't make any sense. There is just a single state repository used by the feature manager. And there is no need to get a list of all available ones.

**Comment by marceloverdijk** [comment]
OK no problem. I was just thinking about more consistency building the featuremanager.
If the feature manager could be build with a StateRepositoryProvider users might be more dynamic to provide the state repository. But maybe the benefit is not that big.

**Comment by chkal** [comment]
Not sure what you mean with "being more dynamic". Users typically set a single configured state repository via the builder. I don't know how a list of "known repository implementations" can help here.
