### ISSUE TITLE
Adding actuator starter to togglz starter complains of duplicate application context

### ISSUE THREAD

**Issue by binkley** [togglz/togglz#156]
Using Togglz 2.3.0.RC1.

Issue demonstrated here: https://github.com/binkley/eg-togglz-spring-boot/commit/32f188cfd879d8bed964ffdcc9f0cf1e22895340.

Adding spring-boot-actuator-starter to my dependencies broke web integration test with complaint:

```
$ cat webapp/target/failsafe-reports/hm.binkley.WebIT.txt 
-------------------------------------------------------------------------------
Test set: hm.binkley.WebIT
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.207 sec <<< FAILURE! - in hm.binkley.WebIT
shouldWire(hm.binkley.WebIT)  Time elapsed: 0.003 sec  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: java.lang.IllegalStateException: There is already a ApplicationContext associated with the context ClassLoader of the current thread!
```

(Disregard togglz-console -- it's in dependenciesManagement block, not a project dependency.  I want to try it next after getting past this issue with actuator.)

**Comment by marceloverdijk** [comment]
Hi @binkley how do you run these tests?

**Comment by binkley** [comment]
```
$ mvn clean verify
```

**Comment by marceloverdijk** [comment]
On top level project:

```
marceloverdijk@marcels-macbook ~/workspace/eg-togglz-spring-boot (master *=)
$ mvn clean verify

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```

and on webapp:

```
marceloverdijk@marcels-macbook ~/workspace/eg-togglz-spring-boot/webapp (master *=)
$ mvn clean install
[ERROR] Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.2:update-parent (update-dependencies) on project webapp: Could not load specified rules from file:///Users/marceloverdijk/workspace/eg-togglz-spring-boot/webapp/maven-version-rules.xml: File: /Users/marceloverdijk/workspace/eg-togglz-spring-boot/webapp/maven-version-rules.xml does not exist -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by marceloverdijk** [comment]
Btw I think the issue is that the IT test is causing multiple `ContextRefreshedEvent` events.
This event binds the application context to a holder (based on classloader) but will fail if it was already binded: https://github.com/togglz/togglz/blob/master/spring-core/src/main/java/org/togglz/spring/util/ContextClassLoaderApplicationContextHolder.java#L39

If this behaviour is normal with IT tests that we might need to remove that check and just re-bind.
What do you think @chkal?

**Comment by chkal** [comment]
Actually I added this additional check and the corresponding `IllegalStateException` because such an exception usually occurs if the `release()` method isn't called correctly which will usually result in class loader leaks which are very hard to find.

Therefore, if Spring doesn't fire a `ContextClosedEvent` before firing a new `ContextRefreshedEvent`, this should perhaps be handled in `TogglzApplicationContextBinderApplicationListener`? Perhaps even with a warning?

You can basically check if there is already an `ApplicationContext` bound to the TCC by calling `ContextClassLoaderApplicationContextHolder#get()` and then call `release()` before calling `bind()`.

Thoughts?

**Comment by marceloverdijk** [comment]
Yes, sound like a reasonable change. Will do that this evening.

**Comment by chkal** [comment]
Awesome. Thanks a lot. :)

**Comment by marceloverdijk** [comment]
@chkal Btw `org.togglz.core.logging.Log` does not have a `warn` method. So probably `info` best option for now.

**Comment by chkal** [comment]
@marceloverdijk Good find! Fixed! :)

https://github.com/togglz/togglz/commit/bf3530094bcbdc05be389e25d55f43adc685e753

**Comment by marceloverdijk** [comment]
Fixed bind issue via bf35300 

On a side note I also fixed/enabled the unit tests of the `togglz-boot-starter` module. In my original Gradle project they were named `*Tests` but renamed them to `*Test`.

**Comment by chkal** [comment]
@marceloverdijk Awesome! Thanks a lot!

@binkley Could you give the latest snapshots a try?

**Comment by binkley** [comment]
@chkal Happy to give it a go in a day or two.  This is my one-and-a-half days out of the week I get to spend at home.  :-)

**Comment by chkal** [comment]
Sure. You shouldn't work on weekends. :)

**Comment by binkley** [comment]
@chkal @marceloverdijk Works for me - thanks!

**Comment by marceloverdijk** [comment]
Thx for feedback!
