### ISSUE TITLE
Add callbacks on feature state changed

### ISSUE THREAD

**Issue by jkubrynski** [togglz/togglz#178]
It would be nice to be able to attach listeners to StateRepository. Currently all applications I saw using toggle were doing that by overriding JDBCStateRepository.

**Comment by hexmind** [comment]
For this feature you should use CompositeStateRepository with 2 your repositories: JDBCStateRepository and ListenerStateRepository
https://www.togglz.org/apidocs/2.3.0.RC2/org/togglz/core/repository/composite/CompositeStateRepository.html

**Comment by parxier** [comment]
@hexmind I don't think this will work out of the box. `CompositeStateRepository`'s default behavior only calls one (last) `StateRepository` for `setFeatureState` calls. It should be possible to achieve desired behavior setting `setterSelection` to call all `StateRepository`s.

**Comment by hexmind** [comment]
You are right, sorry for no details. You need add to your composite constructor:
    this.setSetterSelection(SetterSelection.ALL);

**Comment by chkal** [comment]
I think it really makes sense to think about a separate mechanism for this. It would be nice if one could register listeners at the `FeatureManager`. Something like:

```java
FeatureManager manager = ...;

manager.addFeatureChangeListener( (FeatureState newState) -> {
  // do something here
})
```

But in this case the `FeatureManager` is responsible to inform the listeners. So calling `setFeatureState()` directly on the repository wouldn't trigger any notifications. Not sure if this is a problem. Actually one should use `FeatureManager.setFeatureState()`. I'm not even sure the repository is exposed via the `FeatureManager`.

**Comment by parxier** [comment]
@hexmind Yeah, that'd work, except that there is no `SetterSelection.ALL` enum provided out of the box.

**Comment by anandsunderraman** [comment]
I am looking forward to this. I have `@Cacheable` around a method internally evaluates a feature toggle. My use case for this would be to flush my caches when the feature state changes

**Comment by chkal** [comment]
@anandsunderraman Please note that even if this API gets implemented at some time, you may not get notified for every feature change. Users can always directly modify the feature state in the repository data store directly (the features.properties file, the database table, or wherever).

In the mean time I recommend to implement a custom state repository which wraps the real state repository you are using. Then you can intercept calls to `StateRepository.setFeatureState()` to detect changes to the feature state.

**Comment by anandsunderraman** [comment]
@chkal thanks for the input, sorry for the late response

**Comment by guidosteinacker1969** [comment]
Hi,
as far as I can see, there are several solutions:

1. Add callback support to the FeatureManager
a) by extending the interface + implementing the provided implementations => This would break existing code, where people are implementing FeatureManager on their own.
b) by providing a ListenableFeatureManager, that is a delegate to a FeatureManager with additional support for callbacks
 
2. Add callback support to the StateRepository
a) either by changing the StateRepository interface + updated implementations in the different projects
b) or by adding a ListenableStateRepository, that is a delegate to a StateRepository with additional support for callbacks.

As Christian already mentioned, 1. would be clean, but prone to errors because of state-changes triggered by calling StateRepository.setFeatureState() instead of FeatureManager.setFeatureState().
Solution 2. seams to be more reliable to me. The most simple solution to this would be 2.b), as this is not changing any interfaces, while solving all kinds of 'real-world problems' that I can currently see (including the audit-requirement #179)

Adding support for callbacks to the existing interfaces should at least be postponed to release 3.0.0 - and maybe avoided at all, as this is a feature that is most likely not important for the majority of users.

**Comment by guidosteinacker1969** [comment]
The pull request contains a most simple solution for 2.b)
Please leave a comment, whether or not this is helpful.

**Comment by scheilch** [comment]
This is very helpful as you can do anything when a FeatureState has changed. Maybe there should be another method "onFeatureStateWillChange" before a State changes to also intercept this. A Scenario could be a Backup of all Features before a change happens.

**Comment by IlyasYOY** [comment]
Thank you fore your work in #333!

But this changes are still not released. Are there any information on when it'll be released?

**Comment by bennetelli** [comment]
Looks like it's time to build a release. Thought it would be a good idea to release version 3.0.0 as the next release, but maybe it's a good idea to release the current merged changes earlier.

**Comment by hennr** [comment]
The PR was merged and the release is out since ages.
Good to close this issue then, @bennetelli ?

**Comment by bennetelli** [comment]
yup
