### ISSUE TITLE
FallbackTestFeatureManagerProvider should have lowest priority

### ISSUE THREAD

**Issue by aburmeis** [togglz/togglz#210]
Currently the `FallbackTestFeatureManagerProvider` has a prio of `20` which is more than `10` of `TestFeatureManagerProvider` which is important but less than any other.

Because of this in combination with a poor maven dependency integration IntelliJ always uses the fallback instead of any other when starting an application directly from the IDE (I know the maven integration should also be fixed), but:

Shouldn't the `FallbackTestFeatureManagerProvider` have the least important priority possible (e.g. `Integer.MAX_VALUE`) because it is only a fallback as the name suggests?

**Comment by aburmeis** [comment]
Of course I can work around that by implementing my own `FeatureManagerProvider` with a high priority as a copy of an existing one but it would be great to make this work out of the box.

**Comment by aburmeis** [comment]
But problem will stay the same if I want to test code which uses any production FeatureManagerProvider like this:

```
 FeatureManager own = ...;
StaticFeatureManagerProvider.setFeatureManager(own);
FeatureManager current = FeatureContext.getFeatureManager();
if (current != own) {
    throw new IllegalStateException("Feature manager setup broken, found: " + current);
}
```

**Comment by chkal** [comment]
Actually `TestFeatureManagerProvider` must be processed before `FallbackTestFeatureManagerProvider` because it allows to override the fallback behavior. So if `TestFeatureManagerProvider` is initialized, it will win. If not, the fallback will be applied.

But why is `FallbackTestFeatureManagerProvider` on your classpath at runtime? Perhaps you are using `compile` instead of `test` scope for the testing dependencies?

**Comment by aburmeis** [comment]
Right, the current order of `FeatureManagerProvider` found in core and test is:
* `TestFeatureManagerProvider`
* `FallbackTestFeatureManagerProvider`
* `ThreadLocalFeatureManagerProvider`
* `BeanFinderFeatureManagerProvider`
* `StaticFeatureManagerProvider`
* `ContextClassLoaderFeatureManagerProvider`
* `JNDIFeatureManagerProvider`

So the priority of the `TestFeatureManagerProvider` is completely right but why is the `FallbackTestFeatureManagerProvider` not the last one (acting as a fallback)? My expected order is:

* `TestFeatureManagerProvider`
* `ThreadLocalFeatureManagerProvider`
* `BeanFinderFeatureManagerProvider`
* `StaticFeatureManagerProvider`
* `ContextClassLoaderFeatureManagerProvider`
* `JNDIFeatureManagerProvider`
* `FallbackTestFeatureManagerProvider`

Without that it is impossible to test any code relying on a specific FeatureManagerProvider implementation (e.g. some setup code) because `FeatureContext.getFeatureManager()` will always return the `FallbackTestFeatureManager`.

The problem with the `FallbackTestFeatureManagerProvider` found in my IDE is a bug of the IntelliJ Maven integration and does not occur in production nor running the application from command line.

**Comment by chkal** [comment]
Typically most of the "real" `FeatureManagerProvider` implementation won't work in a unit testing environment. Therefore `FallbackTestFeatureManagerProvider` runs before the real providers and after all other unit test related providers.

I'm still not completely sure if I understand your IDE problem completely. You say that in production everything is fine? So deploying your app in your IDE doesn't work because the togglz testing library gets on your classpath for some reason?

**Comment by aburmeis** [comment]
I hope this has been fixed on IDE side in the meanwhile, and I do not have the setup any more to reproduce, therefore closing.
