### ISSUE TITLE
While using CachingStateRepository have something notify when there is an update to a Feature

### ISSUE THREAD

**Issue by trueblue2704** [togglz/togglz#241]
This is the use case: If the database the features are stored in goes down and the values can't be read functionality that may not have needed the database but checks these feature values fail because we can't get the value from the database. Not setting a timeout in this case works, but only if there is one server that reads these features from the table (since it would have the values in its cache permanently). However if we have multiple servers that implement Togglz, and don't set a timeout on the cache expiring, only the server where setFeature() is called gets the new values from the database.

**Comment by chkal** [comment]
I don't think that setting `ttl` to a large value or `0` is a good idea in this scenario. If you have many servers that read the feature state from a database, you MUST use a small `ttl` value so that the servers get updates fast enough.

If you want to support scenarios where the underlying data source may not be available, you could try to add a custom state repository between the `CachingStateRepository` and the `JDBCStateRepository` which swallows exceptions and return the last value retrieved or something like that.

**Comment by trueblue2704** [comment]
Yeah I agree that makes more sense. Do you think you're going to implement something like that soon?

**Comment by chkal** [comment]
I don't think so. But PRs are welcome.
