### ISSUE TITLE
When will 2.5.0 be released?

### ISSUE THREAD

**Issue by atlanteh** [togglz/togglz#246]
Hi, we want to use togglz with Spring Boot application.yml configuration, but it seems to only work in 2.5.0-SNAPSHOT.
What is the planned release date for 2.5.0?

**Comment by chkal** [comment]
There is no concrete release date yet. I'm still waiting for some confirmations that bugs fixed in the latest snapshots don't occur any more.

However, I think `application.yml` configuration should also work fine with 2.4.x. There have been some changes between 2.4 and 2.5. See the [Updating Notes](https://www.togglz.org/updating-notes.html) for details.

**Comment by atlanteh** [comment]
I see.
Strategy configuration is not supported in 2.4.1. Only enabling and disabling of feature is supported and we must have also strategies.
Currently what we had to do is duplicate the TogglzProperties class to our code and implement a new StateRepository that reads the state from the TogglzProperties.
This kinda sucks but we had no other choice until 2.5.0 gets released.

**Comment by chkal** [comment]
I just checked a few of the pending issues and it looks like we are basically ready for the 2.5.0 release. I'll try to find some time in the next days to do the release. But I don't think this will happen before early next week.

**Comment by atlanteh** [comment]
Any ETA on this?

**Comment by chkal** [comment]
I release 2.5.0.Final today. It is already available on Maven Central.
