### ISSUE TITLE
Togglez work with https

### ISSUE THREAD

**Issue by Pryanic** [togglz/togglz#256]
Hi all.
I am a new user of togglz. I implemented togglz in my project. 
All my servers use https.  And when I change samthing in togglz I got a redirect to http:my.app://togglz-console/index. But my nginx config redirect this request to https:my.app. 
How I can make redirect from togglz edit to togglz-console/index by https?
Let me know if you have any questions

**Comment by chkal** [comment]
This is the code which sends the redirect:

https://github.com/togglz/togglz/blob/db8c4c036acf948f0f0a5fc9eabe9e1d4e639031/console/src/main/java/org/togglz/console/handlers/InitialRedirectHandler.java#L23-L29

The code uses `getRequestURI()` which should return something like `/myapp/togglz` in your case. Therefore the redirect is triggered like this:

    response.sendRedirect("/myapp/togglz/index");

As you see this is a relative URL so it shouldn't change the protocol.

Not sure what is causing this issue in your setup. I recommend to set a break point and see which URL is built.

**Comment by Pryanic** [comment]
I set a break poit I saw that togglz changed protoc. Togglz always use http it' s a huge problem. Can we add possibility to use always https for togglz?

**Comment by chkal** [comment]
Could you share more details? What does `url` look like? What does `event.getRequest().getRequestURI()` return?

**Comment by error418** [comment]
> Can we add possibility to use always https for togglz?

This would break other projects running on http only. Using relative redirects (as togglz does) is the way to go.

As chkal suggested, more information (also about your application/nginx configuration) would be nice.

**Comment by chkal** [comment]
@Pryanic 
I just did some further research on this problem. And I think I finally know what is going on:

Togglz sends the redirect like this:

    response.sendRedirect("<contextPath>/togglz/index"); 

At first this looks fine. But then I found the following statements in the docs of `HttpServletResponse.sendRedirect()`:

> This method can accept relative URLs; the servlet container must convert the relative URL to an absolute URL before sending the response to the client.

So basically your Servlet container is creating the incorrect absolute URL. I guess that's because nginx terminates SSL and sends the request using HTTP to your container. Therefore, the container only sees the HTTP and not the HTTPS address.

There are a few ways to work around this:

1. Use the `proxy_redirect` parameter in your nginx config to rewrite the Location header to the correct URL.
2. Configure your Servlet container to generate the absolute URL correctly. How to do this depends on your container.
3. We adjust Togglz do use an absolute URL for the redirect. This would require to parse the `X-Forwarded-*` headers correctly.

I think the first option is actually the simplest way to go for your case.

I hope this helps. If you like Togglz and this answer helped you to fix your problem, please consider supporting Togglz by becoming a backer on OpenCollective:

https://opencollective.com/togglz/

**Comment by Pryanic** [comment]
First of all I propuse add possibility, additional options for togglz that enable or disable always use https for togglz. It's doesn't affect all curent users and help to resolve my problem.
I can't share nginx config because NDA, but be shore  I use the default and simple features of nginx. 
The togglz config looks like default togglz config:
togglz.console.enabled=true
togglz.console.path=/togglz-console
togglz.console.secured=false
togglz.enabled=true
logging.level.org.togglz=DEBUG
togglz.feature-enums=my.ENUM

The togglz/console/src/main/java/org/togglz/console/handlers/InitialRedirectHandler.java doesn't invoke when I edit one of  toggles kill/switch value. 
Also I have a network response it's  show that when redirect coming the togglz make request use only http. 
![redirect](https://user-images.githubusercontent.com/13783593/32417900-d5f495f4-c268-11e7-832d-f455ae0980cd.png)

**Comment by Pryanic** [comment]
@chkal 
Thank you for you help. I make small help for you. Please merge it if you want https://github.com/togglz/togglz/pull/257 . Add if have intresting idea and you need help let me know.

**Comment by chkal** [comment]
@Pryanic 
You should really double check your reverse proxy and container setup. As I explained in my previous post, Togglz calls `sendRedirect()` with an relative URL, which does nicht change the protocol. Then your container translates this into an absolute URL using the wrong protocol. So you should either configure your container correctly OR use `proxy_redirect` in your nginx config.

**Comment by Pryanic** [comment]
@chkal  Thank you help me a lot.  Do you merge my pull request?

**Comment by chkal** [comment]
I hope you'll be able to fix your issue. Feel free to post on the issue if you have any more problems.

I'll review the PR later...
