### ISSUE TITLE
Add Kotlin support

### ISSUE THREAD

**Issue by BeneStem** [togglz/togglz#292]
Hey there,

so currently Kotlin is not supported because when using „enum class“ there is a compiler error as Kotlin does not like the „name“ method in the „Feature“ interface as it overrides the enum‘s default „name“ method.
When in Java this does not cause any problems and is of course extremely convenient!
But because of how Kotlin works this can not compile in Kotlin at all...

So I tried making an implementation and pull request to support Kotlin. The dumbest approach is obviously renaming the „name“ method in the „Feature“ interface to something different like „id“.

I did that and it works. But before making the pull request I wanted to open an issue and starting a discussion if there might be a solution which does not break the „name“ method convenience in java.

Any suggestions or feedback?

Thank you, best,
/ben

**Comment by chkal** [comment]
Thanks for bringing this up. I'll comment on #293 ...

**Comment by pinkasey** [comment]
I also came across this difficulty - I'm trying a POC of Togglz for my company.

Renaming the method would be great from my perspective (as a new user), but inconvenient for existing users - they will have to update their "Feature" enums to comply with the new name when they upgrade to new version, and they will have to implement a method (name()) they didn't have to before.

I think inheritance can solve this issue, one way or another, not sure.
For now I'm following IntelliJ's advise - made my Feature class a sealed class instead of an enum.
That might be good enough, I'll update.
