### ISSUE TITLE
QueryParameterStrategy not visible in list of available strategies in togglz-console

### ISSUE THREAD

**Issue by mr-springtime** [togglz/togglz#297]
Hi!
I tried to set up a feature with QueryParameterStrategy using Togglz v.2.6.1/Boot 2.0.2, but I could not find it appearing in the list of available strategies in the togglz-console. Does it need to be added to the 
META-INF\services\org.togglz.core.spi.ActivationStrategy file?

Also, is there an example on how to configure it in YML/properties format?

Thanks a lot in advance!

**Comment by ruifigueira** [comment]
Hi,

looking into https://github.com/togglz/togglz/blob/master/servlet/src/main/resources/META-INF/services/org.togglz.core.spi.ActivationStrategy it is actually missing the `QueryParameterActivationStrategy` class.

@chkal , should we add this class into the service file?

**Comment by ruifigueira** [comment]
@mr-springtime, for now, if you create a `/META-INF/services/org.togglz.core.spi.ActivationStrategy` file with `org.togglz.servlet.activation.QueryParameterActivationStrategy` as content, it should become available.

For configuration, I didn't try it, but I think it should be something like:

```
togglz:
  features:
    FOO:
      strategy: query-parameter
      param:
        params: foo=bar,togglz=rocks
```

Note those `param` /  `params` keys: the first one is due to `TogglzProperties.FeatureSpec#getParam`, the second one due to the parameters exposed at `QueryParameterActivationStrategy#getParameters`

**Comment by chkal** [comment]
@ruifigueira Good catch! Very weird. I don't know why the entry is missing. Maybe it got lost in this refactoring?

https://github.com/togglz/togglz/commit/fa17ecc0261f71bb94757d7b999e75a4500f5888#diff-4feaff2a3f4df2be606b35f9f19104bf

Yeah, sure, we should add the missing entry to the provider file.

**Comment by mr-springtime** [comment]
Thanks a lot for the quick feedback!

**Comment by chkal** [comment]
I just added the strategy to the SPI file. So this issue should be fixes in the latest snapshots. Thanks for reporting.
