### ISSUE TITLE
support for functional tests using a rest-api

### ISSUE THREAD

**Issue by ralf-s-lorenz** [togglz/togglz#30]
hello, 
in my current project we're using togglz but we couldn't figure out how to change the feature state of an running web-application under test to ensure that the application works fine in case the feature is enabled and disabled respectively.
The console is not really an option for an automated switch.
Thus we decided to implement an TogglzResource (jersey-REST-Resource) and a RemoteRestStateRepository which work well toghether so that the functional test can switch the feature as it like and test the application.
The Implementation isn't really difficult and if you thing that it fits well into togglz I would be pleased to contribute it to the project.
What do you think?

**Comment by charithdesilva** [comment]
Hi @chkal I'm happy to help on this project as this will be something on my pipeline too. Please let me know.

**Comment by chkal** [comment]
Hey @charithdesilva. Thanks for offering to help.

I thought a lot about how to implement such a restful API for Togglz. My main question is how to handle authentication. Exposing an XML/JSON representation of the feature state should be really easy. Although this should be done without using JAX-RS or something like that, because people may want to use it with Spring or other technologies.

**Comment by hennr** [comment]
Closing this aged issue.
Feel free to open a new issue in case this is still relevant.
