### ISSUE TITLE
Togglz is broken with CSP on

### ISSUE THREAD

**Issue by vidyavgn** [togglz/togglz#342]
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'nonce-aaabbbb' 'strict-dynamic' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-BUxxDlQHd9KRFVq/Agmap1eHN3rEJVlhw/sVJWma000='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by andruhon** [comment]
The solution would be to somehow add config to feed a nonce into toggls. 
To add to scripts like these:
```
<script src="jquery.js"></script>
<script src="bootstrap.js"></script>

<script type="text/javascript">
 jQuery('#strategy').change(function() {
 $('.param').hide('slow');
 $('.strategy'+this.selectedIndex).show('slow');
 });
 </script>
```

**Comment by bennetelli** [comment]
Thanks for your issue. I'm currently working on all the open issues and PRs and the codebase itself, but I think it will take some time to fix your issue. Just because there are lots of other issues open since many years. I will fix these before yours and I'm not working fulltime on this project. 
Will fix this issue as soon as possible.

**Comment by vidyavgn** [comment]
thanks @bennetelli

**Comment by php-coder** [comment]
The best way would be to not inline JS code at all if it's possible.

**Comment by hennr** [comment]
Hi there, I never ran accross this issue.
Please re-open with more details on when and where exactly this happens, in best case with a demo repo.
