### ISSUE TITLE
rename togglz-junit5 artifact to togglz-junit

### ISSUE THREAD

**Issue by bennetelli** [togglz/togglz#432]
Hi there,

I would like to rename the togglz-junit5 artifact to just "togglz-junit" as a replacement of the junit4 integration. I don't want to support junit 4 anymore because I think switching to Junit5 is not that hard and could be done by everyone within 3-4 hours of work.

Let me know if you don't agree with renaming the artifacts. This should probably not lead to any problems, but I just want to be sure.

**Comment by bennetelli** [comment]
see #434

**Comment by leonard84** [comment]
Hi @bennetelli , just came across this, do you really had to spent much time in maintaining the junit4 support. 
AFAIK junit4 has been stable for years so I can't imagine that it required much maintenance effort.

> because I think switching to Junit5 is not that hard and could be done by everyone within 3-4 hours of work.

Some projects have a rather extensive suit of tests, and can't _just_ switch their test in some hours, more like weeks, since you have custom JUnit rules that you need to convert to JUnit 5 extensions.
And also with JUnit Rules support you could use it in Spock tests, since Spock supports JUnit 4 rules, but not Jupiter extensions, since they are too involved.

**Comment by bennetelli** [comment]
hey @leonard84 actually I don't need that much time to maintain it, but I would prefer to drop support of legacy frameworks. I didn't know Spock supports JUnit4 but not Jupiter.. thanks for the hint. I will have to add Junit4 again then.

I raised an issue here and was waiting for feedback, but nobody replied and even weeks/months after releasing the change nobody replied.

In my opinion it's not that bad. Typically fameworks like Spring Boot for example update their dependencies as well. When updating Spring Boot you also get updated Spring Framework dependencies and so on which can also result in an update/migration for users. But it really doesn't matter. I will add junit4 support again so you can use the latest togglz version together with Spock and Junit4.

**Comment by leonard84** [comment]
Hi @bennetelli I understand the desire to get rid of old stuff. 

> I raised an issue here and was waiting for feedback, but nobody replied and even weeks/months after releasing the change nobody replied.

Yeah, I know the problem getting feedback. Most users only check issues when they encounter bugs, or want a feature, so they come after you broke something for them ;). At least this issue was only open for 5 days before it was closed.
