### ISSUE TITLE
Spring Boot Actuator "togglz" endpoint not exposed

### ISSUE THREAD

**Issue by Kondziqq** [togglz/togglz#540]
Hello,
It is probably duplicate of : https://github.com/togglz/togglz/issues/429 but the problem still occurs. I use togglz-spring-boot-starter version 2.9.6 with spring-boot-starter-actuator. There is 404 not found response under localhost:8080/actuator/togglz
I created simple demo showing this issue: https://github.com/Kondziqq/togglz-actuator

**Comment by bennetelli** [comment]
Hey @Kondziqq you missed a Spring Boot Actuator specific configuration in your application.yaml.
Here's a Pull Request containing the fix for your problem: https://github.com/Kondziqq/togglz-actuator/pull/1

It's nothing togglz specific. The Spring actuator just doesn't allow to export custom actuator endpoints by default.
